export default {
  semi: true,
  singleQuote: true,
  tabWidth: 2,
  trailingComma: 'es5',
  printWidth: 100,
  endOfLine: 'lf',
  vueIndentScriptAndStyle: true,
  useTabs: false,
  bracketSpacing: true,
  bracketSameLine: false,
  arrowParens: 'always',
  quoteProps: 'as-needed',
  htmlWhitespaceSensitivity: 'css',
  embeddedLanguageFormatting: 'auto',
};
