export enum ApplicationResource {
  FILE_ROOT = 'public',
  DB_FILE = 'sud.db',
  CONFIG_FILE = 'application.json',
  FIREWALL_RULE = 'Application_Share_Port{port}',
  SHARE_LINK = 'http://{domain}:{port}/share/{uuid}',
}
export enum SteamResource {
  APPLICATION_VDF = '/appcache/appinfo.vdf',
  SCREENSHOT_VDF = '/userdata/{user_id}/760/screenshots.vdf',
  LOCAL_CONFIG_VDF = '/userdata/{user_id}/config/localconfig.vdf',
  LOGIN_USER_VDF = '/config/loginusers.vdf',
  INSTALLED_APPS_ACF = '/steamapps/appmanifest_{game_id}.acf',
  SCREENSHOT = '/userdata/{user_id}/760/remote/',
  AVATAR_CACHE = '/config/avatarcache',
  LIBRARY_COVER_CAP = '/appcache/librarycache',
  GAME_ACHIEVEMENT = '/appcache/stats/UserGameStats_{user_id}_{game_id}.bin',
  USER_GAME_ACHIEVEMENT = '/appcache/stats/UserGameStatsSchema_{game_id}.bin',
  LIB_PIC_FILE = 'library_600x900.jpg',
  LIB_PIC_FILE_LOCAL = 'library_600x900_schinese.jpg',
  LIB_PIC_FILE_CAP = 'library_capsule.jpg',
  LIB_PIC_FILE_CAP_LOCAL = 'library_capsule_schinese.jpg',
  LIB_PIC_HERO = 'library_hero.jpg',
  LIB_PIC_HERO_LOCAL = 'library_hero_schinese.jpg',
  LIB_PIC_LOGO = 'logo.png',
  LIB_PIC_LOGO_LOCAL = 'logo_schinese.png',
  ID_CONVERT = '76561197960265728',
}
