export enum Steam {
  APPLICATION_VDF = '/appcache/appinfo.vdf',
  SCREENSHOT_VDF = '/userdata/{user_id}/760/screenshots.vdf',
  SCREENSHOT = '/userdata/{user_id}/760/remote/',
  LOCAL_CONFIG_VDF = '/userdata/{user_id}/config/localconfig.vdf',
  INSTALLED_APPS_ACF = '/steamapps/appmanifest_{game_id}.acf',
  LOGIN_USER_VDF = '/config/loginusers.vdf',
  AVATOR_CACHE = '/config/avatarcache',
  LIBRARY_COVER_CAP = '/appcache/librarycache',
  LIB_PIC_FILE = 'library_600x900.jpg',
  LIB_PIC_FILE_LOCAL = 'library_600x900_schinese.jpg',
  LIB_PIC_FILE_CAP = 'library_capsule_schinese.jpg',
  LIB_PIC_HERO = 'library_hero.jpg',
  LIB_PIC_HERO_LOCAL = 'library_hero_schinese.jpg',
  LIB_PIC_LOGO = 'logo.png',
  LIB_PIC_LOGO_LOCAL = 'logo_schinese.png',
  ID_CONVERT = '76561197960265728',
}
